name: Git Learning CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check notes file
        run: grep -q "Hello Devops" notes.txt

      - name: Run test
        run: echo "All tests passed!"